// Code generated by "kod generate"; DO NOT EDIT.

package example

import (
	"context"

	"github.com/go-kod/kod-mono/api/graph/model"
)

// GraphService is implemented by [graphImpl],
// which can be mocked with [NewMockGraphService].
type GraphService interface {
	// Todos is implemented by [graphImpl.Todos]
	Todos(ctx context.Context) ([]*model.Todo, error)
	// CreateTodo is implemented by [graphImpl.CreateTodo]
	CreateTodo(ctx context.Context, input model.NewTodo) (*model.Todo, error)
}

// Service is implemented by [component],
// which can be mocked with [NewMockService].
type Service interface {
	// UniqueID is implemented by [component.UniqueID]
	UniqueID(ctx context.Context, req *TestReq) (*TestRes, error)
}
