// Code generated by kod struct2interface; DO NOT EDIT.

package snowflake

import (
	"context"
)

// Service is implemented by [service],
// which can be mocked with [NewMockService].
type Service interface {
	// Gen is implemented by [service.Gen]
	Gen(ctx context.Context, _ *GenReq) (*GenRes, error)
}
