// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/snowflake/kod_gen_interface.go
//
// Generated by this command:
//
//	mockgen -source internal/domain/snowflake/kod_gen_interface.go -destination internal/domain/snowflake/kod_gen_mock.go -package snowflake
//
// Package snowflake is a generated GoMock package.
package snowflake

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// Gen mocks base method.
func (m *MockService) Gen(ctx context.Context, arg1 *GenReq) (*GenRes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Gen", ctx, arg1)
	ret0, _ := ret[0].(*GenRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Gen indicates an expected call of Gen.
func (mr *MockServiceMockRecorder) Gen(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Gen", reflect.TypeOf((*MockService)(nil).Gen), ctx, arg1)
}
