// Code generated by kod struct2interface; DO NOT EDIT.

package snowflake

import (
	"context"
)

// service is a component that implements Service.
type Service interface {
	Gen(ctx context.Context, _ *GenReq) (*GenRes, error)
}
