// Code generated by kod struct2interface; DO NOT EDIT.

package redis

import (
	"context"
)

// SnowflakeRepository is implemented by [snowflake],
// which can be mocked with [NewMockSnowflakeRepository].
type SnowflakeRepository interface {
	// GetUniqId is implemented by [snowflake.GetUniqId]
	GetUniqId(ctx context.Context) (int64, error)
}
