// Code generated by kod struct2interface; DO NOT EDIT.

package redis

import (
	"context"
)

// snowflake is a component that implements SnowflakeRepository.
type SnowflakeRepository interface {
	GetUniqId(ctx context.Context) (int64, error)
}
