// Code generated by MockGen. DO NOT EDIT.
// Source: internal/infra/redis/kod_gen_interface.go
//
// Generated by this command:
//
//	mockgen -source internal/infra/redis/kod_gen_interface.go -destination internal/infra/redis/kod_gen_mock.go -package redis
//
// Package redis is a generated GoMock package.
package redis

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSnowflakeRepository is a mock of SnowflakeRepository interface.
type MockSnowflakeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSnowflakeRepositoryMockRecorder
}

// MockSnowflakeRepositoryMockRecorder is the mock recorder for MockSnowflakeRepository.
type MockSnowflakeRepositoryMockRecorder struct {
	mock *MockSnowflakeRepository
}

// NewMockSnowflakeRepository creates a new mock instance.
func NewMockSnowflakeRepository(ctrl *gomock.Controller) *MockSnowflakeRepository {
	mock := &MockSnowflakeRepository{ctrl: ctrl}
	mock.recorder = &MockSnowflakeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSnowflakeRepository) EXPECT() *MockSnowflakeRepositoryMockRecorder {
	return m.recorder
}

// GetUniqId mocks base method.
func (m *MockSnowflakeRepository) GetUniqId(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUniqId", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUniqId indicates an expected call of GetUniqId.
func (mr *MockSnowflakeRepositoryMockRecorder) GetUniqId(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUniqId", reflect.TypeOf((*MockSnowflakeRepository)(nil).GetUniqId), ctx)
}
