apiVersion: 1

datasources:
  - name: Uptrace Tempo Project 1
    type: tempo
    access: proxy
    url: http://host.docker.internal:14318/api/tempo
    editable: true
    jsonData:
      httpHeaderName1: 'uptrace-dsn'
    secureJsonData:
      httpHeaderValue1: 'http://project1_secret_token@localhost:14317/1'
