// Code generated by "kod generate"; DO NOT EDIT.

package grpc

import (
	"context"

	snowflakev1 "github.com/go-kod/kod-mono/api/grpc/gen/go/snowflake/v1"
)

// Snowflake is implemented by [impl],
// which can be mocked with [NewMockSnowflake].
type Snowflake interface {
	// UniqueId is implemented by [impl.UniqueId]
	UniqueId(ctx context.Context, req *snowflakev1.UniqueIdRequest) (*snowflakev1.UniqueIdResponse, error)
}
