// Code generated by "kod generate". DO NOT EDIT.
//go:build !ignoreKodGen

package grpc

import (
	"context"
	"github.com/go-kod/kod"
	"github.com/go-kod/kod-mono/api/grpc/gen/go/snowflake/v1"
	"github.com/go-kod/kod/interceptor"
	"reflect"
)

// Full method names for components.
const (
	// Snowflake is the full name of the component [github.com/go-kod/kod-mono/internal/infra/grpc/Snowflake].
	Snowflake_ComponentName = "github.com/go-kod/kod-mono/internal/infra/grpc/Snowflake"
	// Snowflake_UniqueId_FullMethodName is the full name of the method [impl.UniqueId].
	Snowflake_UniqueId_FullMethodName = "github.com/go-kod/kod-mono/internal/infra/grpc/Snowflake.UniqueId"
)

func init() {
	kod.Register(&kod.Registration{
		Name:      "github.com/go-kod/kod-mono/internal/infra/grpc/Snowflake",
		Interface: reflect.TypeOf((*Snowflake)(nil)).Elem(),
		Impl:      reflect.TypeOf(impl{}),
		Refs:      ``,
		LocalStubFn: func(ctx context.Context, info *kod.LocalStubFnInfo) any {
			return snowflake_local_stub{
				impl:        info.Impl.(Snowflake),
				interceptor: info.Interceptor,
			}
		},
	})
}

// CodeGen version check.
var _ kod.CodeGenLatestVersion = kod.CodeGenVersion[[0][1]struct{}](`
ERROR: You generated this file with 'kod generate' (codegen
version v0.1.0). The generated code is incompatible with the version of the
github.com/go-kod/kod module that you're using. The kod module
version can be found in your go.mod file or by running the following command.

    go list -m github.com/go-kod/kod

We recommend updating the kod module and the 'kod generate' command by
running the following.

    go get github.com/go-kod/kod@latest
    go install github.com/go-kod/kod/cmd/kod@latest

Then, re-run 'kod generate' and re-build your code. If the problem persists,
please file an issue at https://github.com/go-kod/kod/issues.
`)

// kod.InstanceOf checks.
var _ kod.InstanceOf[Snowflake] = (*impl)(nil)

// Local stub implementations.
// snowflake_local_stub is a local stub implementation of [Snowflake].
type snowflake_local_stub struct {
	impl        Snowflake
	interceptor interceptor.Interceptor
}

// Check that [snowflake_local_stub] implements the [Snowflake] interface.
var _ Snowflake = (*snowflake_local_stub)(nil)

// UniqueId wraps the method [impl.UniqueId].
func (s snowflake_local_stub) UniqueId(ctx context.Context, a1 *snowflakev1.UniqueIdRequest) (r0 *snowflakev1.UniqueIdResponse, err error) {

	if s.interceptor == nil {
		r0, err = s.impl.UniqueId(ctx, a1)
		return
	}

	call := func(ctx context.Context, info interceptor.CallInfo, req, res []any) (err error) {
		r0, err = s.impl.UniqueId(ctx, a1)
		res[0] = r0
		return
	}

	info := interceptor.CallInfo{
		Impl:       s.impl,
		FullMethod: Snowflake_UniqueId_FullMethodName,
	}

	err = s.interceptor(ctx, info, []any{a1}, []any{r0}, call)
	return
}
