// Code generated by kod struct2interface; DO NOT EDIT.

package grpc

import (
	"context"

	snowflakev1 "github.com/go-kod/kod-mono/api/grpc/gen/go/snowflake/v1"
)

// impl is a component that implements Snowflake.
type Snowflake interface {
	UniqueId(ctx context.Context, req *snowflakev1.UniqueIdRequest) (*snowflakev1.UniqueIdResponse, error)
}
