// Code generated by "kod generate". DO NOT EDIT.
//go:build !ignoreKodGen

package gin

import (
	"context"
	"github.com/gin-gonic/gin"
	"github.com/go-kod/kod"
	"github.com/go-kod/kod/interceptor"
	"reflect"
)

func init() {
	kod.Register(&kod.Registration{
		Name:      "github.com/go-kod/kod-mono/internal/adaptor/gin/Controller",
		Interface: reflect.TypeOf((*Controller)(nil)).Elem(),
		Impl:      reflect.TypeOf(controller{}),
		Refs:      `⟦9ddbf0a1:KoDeDgE:github.com/go-kod/kod-mono/internal/adaptor/gin/Controller→github.com/go-kod/kod-mono/internal/app/example/Service⟧`,
		LocalStubFn: func(ctx context.Context, info *kod.LocalStubFnInfo) any {
			interceptors := info.Interceptors
			if h, ok := info.Impl.(interface {
				Interceptors() []interceptor.Interceptor
			}); ok {
				interceptors = append(interceptors, h.Interceptors()...)
			}

			return controller_local_stub{
				impl:        info.Impl.(Controller),
				interceptor: interceptor.Chain(interceptors),
				name:        info.Name,
			}
		},
	})
}

// kod.InstanceOf checks.
var _ kod.InstanceOf[Controller] = (*controller)(nil)

// Local stub implementations.

type controller_local_stub struct {
	impl        Controller
	name        string
	interceptor interceptor.Interceptor
}

// Check that controller_local_stub implements the Controller interface.
var _ Controller = (*controller_local_stub)(nil)

func (s controller_local_stub) UniqueID(a0 *gin.Context) {
	// Because the first argument is not context.Context, so interceptors are not supported.
	s.impl.UniqueID(a0)
	return
}
