// Code generated by kod struct2interface; DO NOT EDIT.

package gin

import (
	gin "github.com/go-kod/kod-ext/server/kgin"
)

// controller is a component that implements Controller.
type Controller interface {
	// @Summary		Get a Unique ID
	// @Description	get unique ID
	// @Consume		x-www-form-urlencoded
	// @Produce		json
	// @Param			request	query		example.TestReq	true	"请求参数"
	// @Success		200		{object}	example.TestRes	"ok"
	// @Router			/uniqueId [get]
	UniqueID(ctx *gin.Context)
}
