// Code generated by kod struct2interface; DO NOT EDIT.

package server

import (
	"context"

	"github.com/go-kod/kod-mono/api/graph"
	snowflakev1 "github.com/go-kod/kod-mono/api/grpc/gen/go/snowflake/v1"
	kgin "github.com/go-kod/kod/ext/server/kgin"
)

// ginImpl is a component that implements GinController.
type GinController interface {
	// @Summary		Get a Unique ID
	// @Description	get unique ID
	// @Consume		x-www-form-urlencoded
	// @Produce		json
	// @Param			request	query		example.TestReq	true	"请求参数"
	// @Success		200		{object}	example.TestRes	"ok"
	// @Router			/uniqueId [get]
	UniqueID(ctx *kgin.Context)
}

// resolver is a component that implements GraphController.
type GraphController interface {
	Query() graph.QueryResolver
	Mutation() graph.MutationResolver
}

// grpcImpl is a component that implements GrpcController.
type GrpcController interface {
	UniqueId(ctx context.Context, req *snowflakev1.UniqueIdRequest) (*snowflakev1.UniqueIdResponse, error)
}
