// Code generated by "kod generate". DO NOT EDIT.
//go:build !ignoreKodGen

package server

import (
	"context"
	"github.com/gin-gonic/gin"
	"github.com/go-kod/kod"
	"github.com/go-kod/kod-mono/api/gen/go/snowflake/v1"
	"github.com/go-kod/kod/interceptor"
	"reflect"
)

func init() {
	kod.Register(&kod.Registration{
		Name:      "github.com/go-kod/kod-mono/internal/adaptor/server/Controller",
		Interface: reflect.TypeOf((*Controller)(nil)).Elem(),
		Impl:      reflect.TypeOf(controller{}),
		Refs:      `⟦fe3cc00c:KoDeDgE:github.com/go-kod/kod-mono/internal/adaptor/server/Controller→github.com/go-kod/kod-mono/internal/app/example/Service⟧`,
		LocalStubFn: func(ctx context.Context, info *kod.LocalStubFnInfo) any {
			interceptors := info.Interceptors
			if h, ok := info.Impl.(interface {
				Interceptors() []interceptor.Interceptor
			}); ok {
				interceptors = append(interceptors, h.Interceptors()...)
			}

			return controller_local_stub{
				impl:        info.Impl.(Controller),
				interceptor: interceptor.Chain(interceptors),
				name:        info.Name,
			}
		},
	})
	kod.Register(&kod.Registration{
		Name:      "github.com/go-kod/kod-mono/internal/adaptor/server/GrpcController",
		Interface: reflect.TypeOf((*GrpcController)(nil)).Elem(),
		Impl:      reflect.TypeOf(grpcImpl{}),
		Refs:      `⟦74eadafa:KoDeDgE:github.com/go-kod/kod-mono/internal/adaptor/server/GrpcController→github.com/go-kod/kod-mono/internal/domain/snowflake/Service⟧`,
		LocalStubFn: func(ctx context.Context, info *kod.LocalStubFnInfo) any {
			interceptors := info.Interceptors
			if h, ok := info.Impl.(interface {
				Interceptors() []interceptor.Interceptor
			}); ok {
				interceptors = append(interceptors, h.Interceptors()...)
			}

			return grpcController_local_stub{
				impl:        info.Impl.(GrpcController),
				interceptor: interceptor.Chain(interceptors),
				name:        info.Name,
			}
		},
	})
	kod.Register(&kod.Registration{
		Name:      "github.com/go-kod/kod/Main",
		Interface: reflect.TypeOf((*kod.Main)(nil)).Elem(),
		Impl:      reflect.TypeOf(Server{}),
		Refs: `⟦120e190c:KoDeDgE:github.com/go-kod/kod/Main→github.com/go-kod/kod-mono/internal/adaptor/server/Controller⟧,
⟦8b746b0c:KoDeDgE:github.com/go-kod/kod/Main→github.com/go-kod/kod-mono/internal/adaptor/server/GrpcController⟧`,
		LocalStubFn: func(ctx context.Context, info *kod.LocalStubFnInfo) any {
			interceptors := info.Interceptors
			if h, ok := info.Impl.(interface {
				Interceptors() []interceptor.Interceptor
			}); ok {
				interceptors = append(interceptors, h.Interceptors()...)
			}

			return main_local_stub{
				impl:        info.Impl.(kod.Main),
				interceptor: interceptor.Chain(interceptors),
				name:        info.Name,
			}
		},
	})
}

// kod.InstanceOf checks.
var _ kod.InstanceOf[Controller] = (*controller)(nil)
var _ kod.InstanceOf[GrpcController] = (*grpcImpl)(nil)
var _ kod.InstanceOf[kod.Main] = (*Server)(nil)

// Local stub implementations.

type controller_local_stub struct {
	impl        Controller
	name        string
	interceptor interceptor.Interceptor
}

// Check that controller_local_stub implements the Controller interface.
var _ Controller = (*controller_local_stub)(nil)

func (s controller_local_stub) UniqueID(a0 *gin.Context) {
	// Because the first argument is not context.Context, so interceptors are not supported.
	s.impl.UniqueID(a0)
	return
}

type grpcController_local_stub struct {
	impl        GrpcController
	name        string
	interceptor interceptor.Interceptor
}

// Check that grpcController_local_stub implements the GrpcController interface.
var _ GrpcController = (*grpcController_local_stub)(nil)

func (s grpcController_local_stub) UniqueId(ctx context.Context, a1 *snowflakev1.UniqueIdRequest) (r0 *snowflakev1.UniqueIdResponse, err error) {

	if s.interceptor == nil {
		r0, err = s.impl.UniqueId(ctx, a1)
		return
	}

	call := func(ctx context.Context, info interceptor.CallInfo, req, res []any) (err error) {
		r0, err = s.impl.UniqueId(ctx, a1)
		res[0] = r0
		return
	}

	info := interceptor.CallInfo{
		Impl:       s.impl,
		Component:  s.name,
		FullMethod: "github.com/go-kod/kod-mono/internal/adaptor/server/GrpcController.UniqueId",
		Method:     "UniqueId",
	}

	err = s.interceptor(ctx, info, []any{a1}, []any{r0}, call)
	return
}

type main_local_stub struct {
	impl        kod.Main
	name        string
	interceptor interceptor.Interceptor
}

// Check that main_local_stub implements the kod.Main interface.
var _ kod.Main = (*main_local_stub)(nil)

